### ISSUE TITLE
Switch with bitmask option

### ISSUE THREAD

**Issue by matteo80** [Mosibi/Midea-heat-pump-ESPHome#25]
Hi Mosibi great job, I have a question for the switch with the bitmask option. When I turn on the switch the bitmask goes on. When I turn off the switch the entire register goes to zero. I tested it both on the PC and on the heatpump. Do you have the same behavior?

**Comment by Mosibi** [comment]
Hi,

Can you tell with exact register that is, then I will have a look at it.

**Comment by matteo80** [comment]
I tried with Register 5, I turned on Silent Mode and it worked. When I turned it off, it also set the climate curve to 0. I then connected the esp to the computer via a usb-rs485 adapter and configured it in slave via modbus slave software. When I turn on individual switches, the individual bitmasks are activated, when I turn off a switch it sets the entire register to 0.

**Comment by Mosibi** [comment]
And then you are referring to this register (5) and bit (7) which you change?? In the current configuration this is still a binary_sensor, so not configurable yet.

```
  # Bit: 7
  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "${entity_prefix} Function Setting Silent Mode Level"
    id: "${devicename}_function_setting_silent_mode_level"
    register_type: holding
    address: 0x5
    bitmask: 0x80
```

Did you change the code yourself to make it possible to set this specific register/bit?

**Comment by matteo80** [comment]
Yes, I changed the settings to switch. 
 ```
switch:
  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "curve_on_off"
    id: curve_on_off
    register_type: holding
    address: 0x5
    bitmask: 0x1000

  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "silent_level"
    id: silent_level
    register_type: holding
    address: 0x5
    bitmask: 0x40


  - platform: modbus_controller
    modbus_controller_id: "${devicename}"
    name: "echo"
    id: echo
    register_type: holding
    address: 0x5
    bitmask: 0x400
 ```
I analyzed better, when I activate one switch set all the others to 0. It's my mistake?
