### ISSUE TITLE
Errors not logged

### ISSUE THREAD

**Issue by CodrutTapu** [Mosibi/Midea-heat-pump-ESPHome#68]
Hello! 

I have a Hyundai PDC and a few days ago i had a H7 error because of a voltage drop.
The error was logged in PDC but not in ESPHome.
 
I checked all these fields

<img width="1471" alt="Screenshot 2024-11-25 at 11 16 15 AM" src="https://github.com/user-attachments/assets/7785511f-2d82-4f22-8612-d9c50d515bab">

Thanks

**Comment by rysiulg** [comment]
OK. But this screen doesn't tell anything. After click on some entity than you can see history status:
![obraz](https://github.com/user-attachments/assets/49a67c0a-ed57-4d80-a853-9798b0a930a6)
If error isn't logged in HA than there could be other kind of problem type... ;)

**Comment by CodrutTapu** [comment]
Sorry for not including more details. As you can see i had a voltage drop to 166V. I had the H7 error displayed on my heatpump screen but it was not logged in HA, as you can see.
Thanks
<img width="2291" alt="Screenshot 2024-11-27 at 8 44 07 AM" src="https://github.com/user-attachments/assets/8c8a345d-8731-4f1f-96d5-7d69ad284ec7">

**Comment by bguettner** [comment]
Hi, It looks like errors are actually logged, but once they are gone the status returns to "OK":
![image](https://github.com/user-attachments/assets/d1295c7d-6115-40f9-a39f-4fd54986b989)
Using with York, ver. 4.1.2.

**Comment by rysiulg** [comment]
If error will be temporary for short time and after that returns to ok it could not being read by controller -in section: modbus_controller->update_interval you have time specified to read from heatpump registry.
Some text valued sensors are visible only after zoom timeframe on chart -if they aren't permanent and changes faster.
Controller reads heatpump modbus and simply send data to homeassisatnt, where some data is recorded some displayed only (not all homeassistant records for history -it depends on config).

**Comment by CodrutTapu** [comment]
@rysiulg the errors are stil displayed in the heatpump menu. Not on the main screen, but in the service screen. Updating update_interval to 1s for example can have any downside ?

**Comment by bkbartk** [comment]
The other day I noticed some statuses not updating in HA either,
I can't tell if the statuses were OK in the esp web interface or not, But I assume the issue is related to ESPhome itself and not related to this implementation.

for me `_status_bit_1_defrosting` was `on` for over an hour, 
but `_active_state` was `Heating`(except for the first 2 minutes where is was defrosting) which is impossible if you check the lambda.
So HA wasn't aware of the status change of the defrosting bit.

If that can happen maybe some other status fails can also happen.

I noticed in the latest esphome release, 2 modbus fixes, maybe they are related.

**Comment by rysiulg** [comment]
> @rysiulg the errors are stil displayed in the heatpump menu. Not on the main screen, but in the service screen. Updating update_interval to 1s for example can have any downside ?

I've tryed gets few seconds and I've get errors with modbus communicate. Get in mind that there is over 200 registers to read and interpret -so read evenm maked in whole range must be splitted by about 100 registers as limitation modbus/esp/library. So 1s is impossible with all sensors -maybe only few registers this will can handle ;)

**Comment by bkbartk** [comment]
I just noticed another sensor not updating in ha. So I went to the esphome webinterface and there the sensor was ok. 
so it seems like a miscommunication between esphome and ha. 
maybe it’s the amount of sensors.

**Comment by Mosibi** [comment]
@bkbartk I did not see that behavior yet. Can you tell more about the Esphome hardware you are using, which esp chip and amount of memory does it have?

if for example your esp chip is not able to keep up, you could change the update_interval to 30 seconds, or remove some registers that you do not need. If it happens often, then I am also curious if you can reproduce it with an older version. In version 4.0.0 I shifted the esp framework from arduino to esp-idf, maybe that is something you can play with.

**Comment by Mosibi** [comment]
> > @rysiulg the errors are stil displayed in the heatpump menu. Not on the main screen, but in the service screen. Updating update_interval to 1s for example can have any downside ?
> 
> I've tryed gets few seconds and I've get errors with modbus communicate. Get in mind that there is over 200 registers to read and interpret -so read evenm maked in whole range must be splitted by about 100 registers as limitation modbus/esp/library. So 1s is impossible with all sensors -maybe only few registers this will can handle ;)

With this amount of entities, the default interval of 60 seconds should be okay. Be aware that the modbus component consolidates as much modbus registers in one call, so setting the interval on one sensor could influence more sensors than expected

**Comment by bkbartk** [comment]
@Mosibi 
this is the behavior I meant
![image](https://github.com/user-attachments/assets/1ca04180-38f6-45a4-9e29-d3c139dfc0b1)
So far I only noticed this for binary sensors.

for hardware I use the module from SvenAr, not sure about the memory.
I use esp-idf, also before v4, arduino framework crashed sometimes for me if a value was set outside the valid boundries.

Today I notide this on v5, but earlier, before updating I noticed the same behavior on another sensor. But If I don't notice it doesn't mean it's not there.

There is one difference between the default and what I use.
For all my esp devices I use a base for wifi etc.... It's like this.
```
wifi:
  id: wifiId
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # power_save_mode: NONE
  power_save_mode: HIGH
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 1h

ota:
  platform: esphome
  password: !secret ota_password
  # safe_mode: true
  # reboot_timeout: 3min
  # num_attempts: 3
  
safe_mode:

web_server:
  port: 80
  version: 3
  local: true
  auth:
    username: admin
    password: !secret web_server_password

button:
  - platform: restart
    name: "${device_name} switch Restart"
    icon: "mdi:restart"
  - platform: safe_mode
    name: "${device_name} Restart (Safe Mode)"
    icon: "mdi:restart-alert"
```

maybe including safe_mode here, is just to much.
but the actual issue is in esphome, not in the yaml.
